######################################################################
# Automatically generated by qmake (3.0) su maaliskuuta 20 16:14:45 2016
######################################################################

TEMPLATE = app
TARGET = 02
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += lecturer.h person.h student.h
SOURCES += e2.cpp lecturer.cpp person.cpp student.cpp
