######################################################################
# Automatically generated by qmake (3.0) ma maaliskuuta 7 16:41:00 2016
######################################################################

TEMPLATE = app
TARGET = 02
INCLUDEPATH += .

QT += widgets
QT += gui

# Input
SOURCES += e3.cpp
