######################################################################
# Automatically generated by qmake (3.0) pe maaliskuuta 25 18:12:01 2016
######################################################################

TEMPLATE = app
TARGET = untitled
INCLUDEPATH += .

QT += widgets
QT += gui
QT += multimedia

TRANSLATIONS = myapp_fi myapp_en_US
# Input
HEADERS += mainwindow.h mytimer.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp mytimer.cpp
