######################################################################
# Automatically generated by qmake (3.0) ma maaliskuuta 7 16:01:17 2016
######################################################################

TEMPLATE = app
TARGET = 08
INCLUDEPATH += .

QT += widgets

# Input
SOURCES += e2.cpp
