######################################################################
# Automatically generated by qmake (3.0) ke maaliskuuta 9 17:14:03 2016
######################################################################

TEMPLATE = app
TARGET = 03
INCLUDEPATH += .

QT+= widgets

# Input
HEADERS += bmi.h
SOURCES += bmi.cpp e3.cpp
