######################################################################
# Automatically generated by qmake (3.0) su maaliskuuta 20 14:33:25 2016
######################################################################

TEMPLATE = app
TARGET = 01
INCLUDEPATH += .

QT += widgets
QT += gui

# Input
HEADERS += person.h
SOURCES += e1.cpp person.cpp
